# Generated by Django 5.2.1 on 2025-06-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='is_staff_reply',
            field=models.BooleanField(default=False),
        ),
    ]
