# Generated by Django 5.2.1 on 2025-06-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ticketreply_is_staff_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='is_staff_reply',
            field=models.BooleanField(default=True),
        ),
    ]
