# Generated by Django 5.2.1 on 2025-06-04 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-rating', 'name'], 'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ['-last_updated'], 'verbose_name': 'محصول فروشگاه', 'verbose_name_plural': 'محصولات فروشگاه\u200cها'},
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='نام کامل فروشگاه را وارد کنید', max_length=255, verbose_name='نام فروشگاه'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='مالک فروشگاه'),
        ),
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(through='store.StoreProduct', to='products.product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.FloatField(default=0, help_text='امتیاز فروشگاه بین 0 تا 5', verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='delivery_time',
            field=models.CharField(choices=[('express', 'اکسپرس (1-2 روز کاری)'), ('standard', 'معمولی (3-5 روز کاری)'), ('long', 'زمانبر (بیش از 5 روز کاری)')], default='standard', max_length=50, verbose_name='زمان تحویل'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stores', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='store.store', verbose_name='فروشگاه'),
        ),
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('store', 'product')},
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='store_store_name_63b397_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['rating'], name='store_store_rating_99a69e_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['store', 'product'], name='store_store_store_i_782dca_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['price'], name='store_store_price_98ff01_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['stock'], name='store_store_stock_f25517_idx'),
        ),
    ]
