# Generated by Django 5.2.1 on 2025-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'فروشنده', 'verbose_name_plural': 'فروشندگان'},
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(max_length=255),
        ),
    ]
